apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-azodha-ingress
  namespace: azodha-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: https://azodha.run.place
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-azodha
            port:
              number: 80
