
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-azodha-ingress
  namespace: azodha-dev
spec:
  ingressClassName: nginx
  rules:
    - host: azodha.run.place
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-azodha
                port:
                  number: 80
