name: Deploy Azodha to EKS
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CLUSTER_NAME: EKS_CLOUD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name $CLUSTER_NAME

      - name: Verify cluster access
        run: kubectl get nodes

      # -------- APPLY MANIFESTS IN CORRECT ORDER --------

      - name: Apply Namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Apply Persistent Volume / PVC
        run: kubectl apply -f k8s/pv.yaml

      - name: Deploy OpenTelemetry
        run: kubectl apply -f k8s/opentelemetry.yaml

      - name: Deploy Application
        run: kubectl apply -f k8s/deployment.yaml

      - name: Deploy Service
        run: kubectl apply -f k8s/service.yaml

      - name: Deploy HPA
        run: kubectl apply -f k8s/HorizontalPodAutoscaler.yaml

      - name: Deploy Ingress
        run: kubectl apply -f k8s/ingress.yaml

      - name: Verify Deployment
        run: |
          kubectl get all -n azodha-dev
          kubectl get ingress -n azodha-dev
          kubectl get hpa -n azodha-dev
